/**
 * AI Discovery System Types
 * 
 * Type definitions for the AI-Assisted Discovery & Prediction pipeline.
 * All numeric analysis is deterministic; LLaMA is used only for reasoning.
 */

// ============================================================================
// STATISTICAL ANALYSIS TYPES
// ============================================================================

/** Basic descriptive statistics for a numeric field */
export interface FieldStatistics {
  count: number
  validCount: number
  nullCount: number
  nullRatio: number
  mean: number
  median: number
  std: number
  min: number
  max: number
  q1: number  // 25th percentile
  q3: number  // 75th percentile
  iqr: number // Interquartile range
}

/** Correlation between two fields */
export interface FieldCorrelation {
  field1: string
  field2: string
  coefficient: number  // Pearson correlation coefficient
  strength: "weak" | "moderate" | "strong"
  direction: "positive" | "negative" | "none"
  pValue?: number
}

/** Linear trend analysis result */
export interface TrendAnalysis {
  field: string
  timeField: string
  slope: number
  intercept: number
  rSquared: number
  direction: "increasing" | "decreasing" | "stable"
  significance: "low" | "medium" | "high"
}

/** Outlier detection result */
export interface OutlierInfo {
  field: string
  method: "zscore" | "iqr"
  outlierIndices: number[]
  outlierCount: number
  outlierRatio: number
  threshold: number
}

/** Analysis result for a single numeric field */
export interface NumericFieldAnalysis {
  fieldName: string
  physicalQuantity?: string
  unit?: string
  stats: FieldStatistics
  outliers: OutlierInfo
  correlations: FieldCorrelation[]
  trend?: TrendAnalysis
}

/** Complete analysis for a single dataset */
export interface DatasetAnalysis {
  datasetId: string
  datasetName: string
  rowCount: number
  columnCount: number
  numericFieldCount: number
  categoricalFieldCount: number
  numericFields: NumericFieldAnalysis[]
  topCorrelations: FieldCorrelation[]
  hasTimeField: boolean
  timeFieldName?: string
  analysisTimestamp: string
}

/** Cross-dataset comparison result */
export interface CrossDatasetComparison {
  field: string
  physicalQuantity: string
  datasets: {
    datasetId: string
    datasetName: string
    stats: FieldStatistics
  }[]
  distributionShift: "none" | "minor" | "significant"
  commonRange: { min: number; max: number }
  overlapRatio: number
}

/** Complete deterministic analysis output */
export interface DeterministicAnalysisResult {
  datasets: DatasetAnalysis[]
  crossDatasetComparisons: CrossDatasetComparison[]
  analysisTimestamp: string
  totalRows: number
  totalNumericFields: number
}

// ============================================================================
// LLAMA INSIGHT TYPES
// ============================================================================

/** Type of insight generated by LLaMA */
export type InsightType = "pattern" | "anomaly" | "correlation" | "summary" | "comparison"

/** Confidence level for insights and predictions */
export type ConfidenceLevel = "low" | "medium" | "high"

/** Single insight generated by LLaMA */
export interface AIInsight {
  id: string
  type: InsightType
  title: string
  explanation: string
  confidence: ConfidenceLevel
  relatedFields: string[]
  relatedDatasets: string[]
  scientificContext?: string
}

/** Single prediction generated by LLaMA (interpretive only) */
export interface AIPrediction {
  id: string
  targetField: string
  basis: string  // What data the prediction is based on
  description: string
  confidence: ConfidenceLevel
  caveat: string  // Uncertainty statement
  relatedDatasets: string[]
}

// ============================================================================
// COMPUTED NUMERIC RESULTS (From Python Analytics Engine)
// ============================================================================

/** Enhanced field statistics with p-values */
export interface EnhancedFieldStatistics {
  field: string
  count: number
  null_count: number
  mean: number
  median: number
  std: number
  min: number
  max: number
  range: number
  q1: number
  q3: number
  iqr: number
  skewness: number
  kurtosis: number
  is_normal_distribution: boolean
  normality_p_value: number
  coefficient_of_variation: number
}

/** Correlation with both Pearson and Spearman + p-values */
export interface EnhancedCorrelation {
  x: string
  y: string
  pearson_r: number
  pearson_p: number
  spearman_r: number
  spearman_p: number
  n_samples: number
  is_significant: boolean
}

/** Regression result with full coefficients */
export interface RegressionResult {
  target: string
  feature: string
  slope: number
  intercept: number
  r2: number
  correlation: number
  p_value: number
  std_error: number
  n_samples: number
  sample_predictions: Array<{
    input_value: number
    predicted_value: number
    confidence_interval: [number, number]
  }>
}

/** Outlier with actual values and z-scores */
export interface EnhancedOutlier {
  field: string
  total_outliers: number
  outlier_ratio: number
  mean: number
  std: number
  lower_bound: number
  upper_bound: number
  outlier_details: Array<{
    row_index: number
    value: number
    z_score: number
    is_extreme: boolean
  }>
}

/** Computed numeric prediction (NOT from LLM) */
export interface ComputedPrediction {
  type: "regression_based"
  target_field: string
  predictor_field: string
  model_r2: number
  model_equation: string
  predictions_at_boundaries: {
    at_min: { input: number; predicted: number; ci_lower: number; ci_upper: number }
    at_mean: { input: number; predicted: number; ci_lower: number; ci_upper: number }
    at_max: { input: number; predicted: number; ci_lower: number; ci_upper: number }
  }
  interpretation_hint: string
  confidence: "high" | "medium" | "low"
}

/** Complete Python analytics result */
export interface PythonAnalyticsResult {
  summary: {
    total_rows: number
    total_columns: number
    numeric_columns: number
    numeric_column_names: string[]
  }
  field_statistics: EnhancedFieldStatistics[]
  correlations: EnhancedCorrelation[]
  regressions: RegressionResult[]
  outliers: EnhancedOutlier[]
  computed_predictions: ComputedPrediction[]
  analysis_complete: boolean
  error?: string
  datasetId?: string
  datasetName?: string
  processingTimeMs?: number
}

/** Complete LLaMA response */
export interface LLaMAInsightResponse {
  insights: AIInsight[]
  predictions: AIPrediction[]
  summary: string
  modelUsed: string
  generatedAt: string
  disclaimer: string
}

// ============================================================================
// UI STATE TYPES
// ============================================================================

/** Dataset selection state */
export interface DatasetSelection {
  datasetId: string
  datasetName: string
  rowCount: number
  numericColumns: number
  selected: boolean
}

/** AI Discovery pipeline state */
export type DiscoveryPipelineState = 
  | "idle"
  | "selecting"
  | "analyzing"
  | "generating_insights"
  | "complete"
  | "error"

/** Error information */
export interface DiscoveryError {
  stage: "analysis" | "llama" | "rendering"
  message: string
  details?: string
  recoverable: boolean
}

/** Complete AI Discovery result */
export interface AIDiscoveryResult {
  analysis: DeterministicAnalysisResult
  insights: LLaMAInsightResponse | null
  selectedDatasetIds: string[]
  completedAt: string
  error?: DiscoveryError
}

// ============================================================================
// API TYPES
// ============================================================================

/** Request body for AI insights API */
export interface AIInsightsRequest {
  analysis: DeterministicAnalysisResult
  options?: {
    maxInsights?: number
    maxPredictions?: number
    focusAreas?: string[]
    forceRefresh?: boolean
  }
}

/** Response from AI insights API */
export interface AIInsightsResponse {
  success: boolean
  insights?: LLaMAInsightResponse
  error?: string
  fallbackMessage?: string
}
